### ISSUE TITLE
Representation of Act of Modifying/Updating/Revising a Document

### ISSUE THREAD

**Issue by daltontc** [CommonCoreOntology/CommonCoreOntologies#12] opened 2018-05-22 13:28 UTC
My team is currently trying to create an ontology where the primary focus is tracking documents through a life cycle. With this, we need to represent how a document can be updated throughout the span of its life. I went through the CCO and PLC to see if there was anything that could represent this, but could only find things that only vaguely apply. I propose that the CCO add an Act of Modifying/Updating/Revising a Document in order to fill in the missing gap.

**Comment by bdonohue29** [comment] 2018-05-22 14:17
Thanks for the suggestion! I think the closest we have is "Act of Artifact Modification" in the Event Ontology, a class which is meant to capture changing the qualities, functions, etc., of an artifact, including Documents

Note: I am not sure it would be helpful to add a class, e.g., "Act of Document Modification". The reason is that "Act of Document Modification" would be semantically equivalent to the graph "Act of Artifact Modification has_participant Document". That is, one could express the fact that a Document is being modified without recourse to a special kind of act.

(As an analogy: It would be redundant to add classes like "Act of Driving a Red Car," "Act of Driving a Blue Car," etc. Rather, we'd advocate saying something like, "Act of Driving has_participant Automobile" and then "Automobile has_quality RedColor". You get all the semantic content you need by building out the graph, rather than packing everything into a very specific class.)

That being said, I agree that _editing_ or _revising_ a document is more specific than the generic modification concept, so there's definitely room there for expanding our hierarchy in this way. So again, thanks for the suggestion!

**Comment by daltontc** [comment] 2018-05-24 18:00
If editing or revising a document is something that you may or may not add to CCO, is there a way that I could be updated about it?

**Comment by mark-jensen** [comment] 2018-05-24 18:19
Ideally, when a new version of the ontology is uploaded to the repo, any issues which are addressed with fixes or additions will be noted in comments for the commit. In some cases an issue will be closed outright with a commit. Since you started the issue, you should be automatically notified when the issue is updated or closed. It may be necessary for you to make yourself a watcher of the repo to get all notifications. 

Also, when making term requests, if possible, the more information the better. Eg- enumerating the needed terms, proposing definitions, describing the intended usage, etc. All are helpful for us in deciding if the terms need to be added and then creating them. 

We are due for a new release soon, so expect an update within the month.

**Comment by daltontc** [comment] 2018-07-06 19:57
Any update on this?

**Comment by daltontc** [comment] 2018-08-20 14:03
Is this happening?

**Comment by mark-jensen** [comment] 2018-08-30 19:37
@daltontc Sorry for they delay in responding. Are you looking for one fairly general term that covers any possible act of modifying a document, eg- `Act of Document Modification`? Or several for representing more specific acts of modification?

**Comment by oliviahobai** [comment] 2024-08-18 14:39
This term request would fit well in Jonathan Vajda's work bridging the [CCO into Document Acts](https://github.com/jonathanvajda/cco-d-acts), but may be out of scope to the CCO suite as it stands.

**Closed by oliviahobai** 2024-08-18 14:39 UTC
Labels: relevant-mid-level-ontology-std
